# Generated by Django 4.2 on 2023-04-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'about_pricing',
                'db_table': 'about_pricing',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_branches', models.IntegerField()),
                ('number_of_awards', models.IntegerField()),
                ('happy_customers', models.IntegerField()),
                ('staff', models.IntegerField()),
            ],
        ),
    ]
