# Generated by Django 4.2 on 2023-04-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_aboutpricing_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'about_product_detail',
                'db_table': 'about_product_detail',
            },
        ),
        migrations.CreateModel(
            name='SecondBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'second_blog',
                'db_table': 'second_blog',
            },
        ),
    ]
